### ISSUE TITLE
coordinate Globus docs with Delta and Storage

### ISSUE THREAD

**Issue by craigsteffen** [ncsa/ncsa_system_documentation#15]
Craig to coordinate with Brett and JD Maloney about what should be in the global Globus doc, and coordinate that with the various system Globus pages.

**Comment by lhelms2** [comment]
Alignment meeting held 1/12, attendees: Brett, Sean, Craig, Lillian.

Notes:
- Globus account link for Campus Cluster - UIUC
- Globus account link for Delta, Nightingale, and Hydro - NCSA
- Box and Google, and Shared Globus endpoints currently only available for ICC, these sections will stay in ICC docs

Next steps:

1. Update/refine common hub page
2. Submit for review/approval
3. Make common page live in hub
4. Whittle down system-specific Globus pages/sections (and link to Hub page). Info will be duplicated in Hub and system-specific pages for a short period of time while system-specific pages are updated to refer to Hub page.

**Comment by lhelms2** [comment]
Craig sent email to JD, Brett, Greg, and Sean 1/17 to ask about preference between the below Globus account setup options for users:

1. Users creating separate, stand-alone Globus account (and linking UIUC and/or NCSA identities, as required)
2. Creating Globus account using UIUC authentication (and linking NCSA identity, as required)

Still pending response, as of 1/29.

Current Globus setup steps are written for Option 2 above, if Option 1 is preferred, Lillian will update the setup steps to match.

**Comment by lhelms2** [comment]
Closing. Globus hub page is live.
